server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3308/productdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
#  config:
#    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

