version: '3'
services:
  database-shopping:
    platform: linux/x86_64
    image: mysql:8.0.28
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    entrypoint:
      sh -c "
      echo '
      CREATE DATABASE IF NOT EXISTS productdb;
      CREATE DATABASE IF NOT EXISTS user;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"